"""
Export Manager - Export documents to various formats (Obsidian, Markdown, etc.)
All completely free, no API calls
"""
from typing import Dict, Any, List
from pathlib import Path
import json
import datetime


class ExportManager:
    """Manages document export to various formats"""

    def export_to_markdown(
        self,
        content: str,
        metadata: Dict[str, Any] = None,
        toc: List[Dict] = None,
        sections: List[Dict] = None,
        output_path: str = None
    ) -> str:
        """
        Export to standard Markdown

        Args:
            content: Markdown content
            metadata: Document metadata
            toc: Table of contents
            sections: Document sections
            output_path: Optional output file path

        Returns:
            Markdown string
        """
        parts = []

        # Add frontmatter (YAML)
        if metadata:
            parts.append("---")
            parts.append(f"title: {metadata.get('title', 'Untitled')}")
            parts.append(f"date: {datetime.datetime.now().strftime('%Y-%m-%d')}")

            if metadata.get('page_count'):
                parts.append(f"pages: {metadata['page_count']}")
            if metadata.get('layout_type'):
                parts.append(f"layout: {metadata['layout_type']}")
            if metadata.get('tags'):
                parts.append(f"tags: [{', '.join(metadata['tags'])}]")

            parts.append("---\n")

        # Add TOC if available
        if toc and len(toc) > 0:
            parts.append("## Table of Contents\n")
            for item in toc:
                indent = "  " * (item['level'] - 1)
                parts.append(f"{indent}- [{item['title']}](#) (p.{item['page']})")
            parts.append("\n---\n")

        # Add main content
        parts.append(content)

        markdown = '\n'.join(parts)

        # Write to file if path provided
        if output_path:
            Path(output_path).write_text(markdown, encoding='utf-8')

        return markdown

    def export_to_obsidian(
        self,
        content: str,
        metadata: Dict[str, Any] = None,
        toc: List[Dict] = None,
        vault_path: str = None,
        filename: str = None
    ) -> str:
        """
        Export to Obsidian-compatible Markdown

        Obsidian format includes:
        - YAML frontmatter
        - Wiki-style links [[link]]
        - Tags as #tag
        """
        parts = []

        # Obsidian frontmatter
        if metadata:
            parts.append("---")

            # Standard fields
            if metadata.get('title'):
                parts.append(f"title: \"{metadata['title']}\"")

            parts.append(f"created: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}")

            # Custom fields
            if metadata.get('page_count'):
                parts.append(f"pages: {metadata['page_count']}")
            if metadata.get('layout_type'):
                parts.append(f"layout-type: {metadata['layout_type']}")
            if metadata.get('section_count'):
                parts.append(f"sections: {metadata['section_count']}")

            # Tags (Obsidian format)
            if metadata.get('tags'):
                tags_str = ', '.join([f'"{tag}"' for tag in metadata['tags']])
                parts.append(f"tags: [{tags_str}]")

            parts.append("---\n")

        # Add TOC with Obsidian links
        if toc and len(toc) > 0:
            parts.append("## 📑 Table of Contents\n")
            for item in toc:
                indent = "  " * (item['level'] - 1)
                # Convert to Obsidian heading link format
                heading_link = item['title'].lower().replace(' ', '-')
                parts.append(f"{indent}- [[#{heading_link}|{item['title']}]]")
            parts.append("\n---\n")

        # Process content for Obsidian
        # (Could add wiki-link conversion here if needed)
        parts.append(content)

        # Add metadata footer
        parts.append("\n\n---\n")
        parts.append("*Generated by VaultOCR-AI*")

        markdown = '\n'.join(parts)

        # Write to Obsidian vault if path provided
        if vault_path and filename:
            output_file = Path(vault_path) / filename
            output_file.parent.mkdir(parents=True, exist_ok=True)
            output_file.write_text(markdown, encoding='utf-8')

        return markdown

    def export_to_json(
        self,
        content: str,
        metadata: Dict[str, Any] = None,
        toc: List[Dict] = None,
        sections: List[Dict] = None,
        paragraphs: List[Dict] = None,
        output_path: str = None
    ) -> Dict[str, Any]:
        """
        Export to structured JSON format

        Useful for:
        - API integration
        - Database import
        - Further processing
        """
        data = {
            'content': content,
            'metadata': metadata or {},
            'toc': toc or [],
            'sections': sections or [],
            'paragraphs': paragraphs or [],
            'exported_at': datetime.datetime.now().isoformat()
        }

        if output_path:
            Path(output_path).write_text(
                json.dumps(data, ensure_ascii=False, indent=2),
                encoding='utf-8'
            )

        return data

    def export_to_notion(
        self,
        content: str,
        metadata: Dict[str, Any] = None,
        toc: List[Dict] = None
    ) -> str:
        """
        Export to Notion-compatible Markdown

        Notion has some specific requirements:
        - Headings with #
        - Callouts with > 💡
        - Code blocks
        - Tables
        """
        parts = []

        # Title (Notion page title)
        if metadata and metadata.get('title'):
            parts.append(f"# {metadata['title']}\n")

        # Metadata as callout
        if metadata:
            parts.append("> 💡 **Document Info**")
            parts.append(">")

            if metadata.get('page_count'):
                parts.append(f"> - Pages: {metadata['page_count']}")
            if metadata.get('layout_type'):
                parts.append(f"> - Layout: {metadata['layout_type']}")
            if metadata.get('section_count'):
                parts.append(f"> - Sections: {metadata['section_count']}")

            parts.append("\n")

        # TOC as toggle list (Notion format)
        if toc and len(toc) > 0:
            parts.append("## Table of Contents\n")
            for item in toc:
                indent = "  " * (item['level'] - 1)
                parts.append(f"{indent}- {item['title']}")
            parts.append("\n---\n")

        # Main content
        parts.append(content)

        return '\n'.join(parts)

    def export_batch(
        self,
        documents: List[Dict[str, Any]],
        format: str = 'markdown',
        output_dir: str = None
    ) -> List[str]:
        """
        Export multiple documents

        Args:
            documents: List of document dicts with content, metadata, etc.
            format: 'markdown', 'obsidian', 'json', 'notion'
            output_dir: Output directory

        Returns:
            List of output file paths
        """
        output_paths = []
        output_dir = Path(output_dir) if output_dir else Path('.')
        output_dir.mkdir(parents=True, exist_ok=True)

        for doc in documents:
            title = doc.get('metadata', {}).get('title', 'untitled')
            filename = f"{title.replace(' ', '_')}.{format if format != 'obsidian' else 'md'}"
            output_path = output_dir / filename

            if format == 'markdown':
                self.export_to_markdown(
                    doc.get('content', ''),
                    doc.get('metadata'),
                    doc.get('toc'),
                    doc.get('sections'),
                    str(output_path)
                )
            elif format == 'obsidian':
                self.export_to_obsidian(
                    doc.get('content', ''),
                    doc.get('metadata'),
                    doc.get('toc'),
                    str(output_dir),
                    filename
                )
            elif format == 'json':
                self.export_to_json(
                    doc.get('content', ''),
                    doc.get('metadata'),
                    doc.get('toc'),
                    doc.get('sections'),
                    doc.get('paragraphs'),
                    str(output_path.with_suffix('.json'))
                )
            elif format == 'notion':
                markdown = self.export_to_notion(
                    doc.get('content', ''),
                    doc.get('metadata'),
                    doc.get('toc')
                )
                output_path.write_text(markdown, encoding='utf-8')

            output_paths.append(str(output_path))

        return output_paths
